# Generated by Django 3.2.23 on 2023-12-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigna', '0005_auto_20231205_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Pigna', 'Pigna'), ('CS', 'CS')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
